// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD82KraoFEv1uhaEHVBiS6u5otSSVGJoxk',
    appId: '1:941940225099:web:b34103b02269a8f20ac9ce',
    messagingSenderId: '941940225099',
    projectId: 'henhung-99234',
    authDomain: 'henhung-99234.firebaseapp.com',
    storageBucket: 'henhung-99234.firebasestorage.app',
    measurementId: 'G-6JS01YHDES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAnO3-W3iNpJ9Y1JDqHLGcZAGvZFbFPsc',
    appId: '1:941940225099:android:41fedd65e72e8dad0ac9ce',
    messagingSenderId: '941940225099',
    projectId: 'henhung-99234',
    storageBucket: 'henhung-99234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKvE5ckik_5oXEkUVmdqtL0enSHao__xc',
    appId: '1:941940225099:ios:5bab4d893a2553490ac9ce',
    messagingSenderId: '941940225099',
    projectId: 'henhung-99234',
    storageBucket: 'henhung-99234.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKvE5ckik_5oXEkUVmdqtL0enSHao__xc',
    appId: '1:941940225099:ios:5bab4d893a2553490ac9ce',
    messagingSenderId: '941940225099',
    projectId: 'henhung-99234',
    storageBucket: 'henhung-99234.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD82KraoFEv1uhaEHVBiS6u5otSSVGJoxk',
    appId: '1:941940225099:web:e35ee6f30627b08c0ac9ce',
    messagingSenderId: '941940225099',
    projectId: 'henhung-99234',
    authDomain: 'henhung-99234.firebaseapp.com',
    storageBucket: 'henhung-99234.firebasestorage.app',
    measurementId: 'G-3XN5EEZT7Z',
  );
}
